---
- hosts: master
  become: yes
  become_user: postgres
  become_method: sudo

  tasks:
    - name: create citus extension
      shell: psql -d database -c "CREATE EXTENSION citus;"
    - name: crate extension postgis
      shell: psql -d database -c "CREATE EXTENSION postgis;"
    - name: add workers
      shell: psql -d database -c "SELECT * FROM master_add_node('{{ item }}', 5432);"
      - debug: msg="host is {{item}}"
        with_items: "{{ groups['worker'] }}"

