---
- hosts: all
  become: yes
  become_user: root
  become_method: sudo
  gather_facts: yes
  vars:
    pgversion: 11
    citusversion: 8.3
    postgisversion: 2.5

  roles:
    - apt-pgdg
    - postgresql-install
    - citus-install
    - postgresql-config
