---
- name: import pgdg key
  apt_key:
    url=https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state=present

- name: pgp repository
  apt_repository:
    repo='deb http://apt.postgresql.org/pub/repos/apt {{ansible_distribution_release}}-pgdg main'
    state=present

- name: install pgdg-keyring
  apt:
    update_cache=yes
    cache_valid_time=3600
    pkg=pgdg-keyring
