---
- name: install pgdg-keyring
  apt:
    update_cache=yes
    cache_valid_time=3600
    pkg=pgdg-keyring

- name: install postgresql-{{ pgversion }}
  apt:
    update_cache=yes
    cache_valid_time=3600
    pkg=postgresql-{{ pgversion }}

- name: postgresql-contrib-{{ pgversion }}
  apt:
    update_cache=yes
    cache_valid_time=3600
    pkg=postgresql-contrib-{{ pgversion }}

- name: Install Packages
  apt: >
    pkg={{item}}
    state=installed
    update-cache=yes
  with_items:
    - build-essential
    - python-dev
    - python-setuptools
    - python-psycopg2
    - postgresql-{{ pgversion }}-postgis-{{ postgisversion }}
    - postgresql-{{ pgversion }}-pgrouting
    - libpq-dev
    - pgtop

