---
- name: create database
  postgresql_db:
    name: database
    encoding: UTF-8

- name: create extension citus
  postgresql_ext:
    name: citus
    db: database

- name: create extension postgis
  postgresql_ext:
    name: postgis
    db: database
